# Generated by Django 5.2.5 on 2025-08-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга'), ('song', 'Песня'), ('other', 'Другое')], max_length=20, verbose_name='Тип'),
        ),
    ]
