# Generated by Django 4.2.2 on 2025-08-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='updated_at',
        ),
    ]
